name: Run Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install minimal nightly
      run: rustup default nightly

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
